### ISSUE TITLE
Test scaffolding command or A/A test generation

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#8]
To make it easy for new users to get started, we could have a test scaffolding command to create a `live` A/A test in the waves directory:

```yml
id: aa1
name: AA test 1
sampleRate: 1
state: live
trigger: trigger.js
recipes:
  0:
    name: A1
  1:
    name: A2
```

```js
function trigger(test)
{
  test.activate();
}
```

A simple gulp command would generate the files needed:

```
gulp scaffold
```

Not attached to this particular naming - might be a better term we could use here.
